### ISSUE TITLE
The aapc data frame in the output is empty

### ISSUE THREAD

**Issue by tianliu88** [DanChaltiel/nih.joinpoint#12] opened 2024-11-25 08:46 UTC
**Describe the new feature**
The aapc data frame in the output is empty. When performing joinpoint analysis using the nih.joinpoint package, I found that the aapc data frame was empty. I have used this before without encountering this issue. I am not sure what went wrong this time. The Joinpoint development version software is version 4.9, and the R software version is 4.4.1. I was using the example data

**Known workaround**
options(joinpoint_path = "D:/Program Files/Joinpoint Command/jpCommand.exe")
run_opt <- run_options(model = "ln", max_joinpoints = 3, 
                       n_cores = 3)

jp = joinpoint(nih_sample_data, x=year, y=rate, by=sex, se=se,
               run_opts=run_opt, export_opts=export_opt)

![image](https://github.com/user-attachments/assets/e233229f-952d-4b5e-89e9-d92adbd1518f)

**Comment by DanChaltiel** [comment] 2024-11-25 09:24
Hi,
This is not a bug in the package, but the output of the NIH software, so there is nothing I can do about it.
You can see that by running `browse(jp)` to see the text output of `session_run.aapcexport.txt`, which should be empty.
This may be due to the particular structure of the NIH example sample.
If you have the GUI version of joinpoint, you can try it there to see if it shows a warning or so.

I'm closing this issue in favor of #13 (add a warning).

**Closed as completed by DanChaltiel** 2024-11-25 09:24 UTC
Labels: enhancement
